---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgAoB0hcRjoms8mfq8zzlmj0goJFXbjwqh49q7loKn3P0zamFnpLjR5YuG4wsi0s/V98mcwXo9a1U9cQtBQYN2e49lKS4u1jlcCByhPTYxPuC9UHEJRY8qoGho+TkDi37l6PNOHd9G6qhu97fRHIu/tzzaO9lUWunLUFO1drDdxfeymbMDf5/ELEhfD/baNqpgqwWF2SRBFzi+V3UqwH3X82CHocKTupD1mjIx2F8smA90hLEOHptG/6pR27ofGotnZ19mQ/cwGbBhgFVLKeBMAwzVPjTQlruN9eBWrdFsGoZdCYqSzn8APFNbidIf6YkFUph+FrHQSjRu6f/V1q7p60e8PP26/96ZTI9QmVVOEtPQ4Gb+kzweyntZ5yAiXPjV+RJbVIm7yuSSOn+RaaODzDw5GYh9TTGCYcKQoRI9ToScEP1V13UkPK418kI0BFTRzTsgjvgZMu2b/D7aY3Ds/BAt9kJTztAlTIiH608XIxWOvbWiAH3bawudKYe6Htl+70VGJCATc64fqq9NF7RWS0yV2pHITOgWvBiVr4xWdtkL5T4EtBmBspjgLQnB9U3MTz1pZLb9zuIQmZOaIZVlh5cP8BPhFo7h4bf7kFBfkjzM1sPcp8btLMtBp+CV3kUqrV0rEUXgwyulugYwZZBAGHaIkK4Nt/iAzGg5Sa2c1IQ3E8NSqZhRR9y2IlCvoJeV4L3EfIFe1c6uYJTutCPvLJqNW4R+iwO5vVD/wKDnruxBmpjKtHpZo=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
