apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-deployment
spec:
  selector:
    matchLabels: 
      app: caddy
  replicas: 1
  template:
    metadata: 
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:alpine
          ports:
          - containerPort: 80
             name: http
          volumeMounts:
          - name: caddy-config
            mountPath: /etc/caddy/
            readOnly: true
      volumes:
      - name: caddy-config
        configMap:
          name: caddy-config
